### ISSUE TITLE
[BUG] Issue with Asynchronous command dispatch

### ISSUE THREAD

**Issue by Kyrobi** [Mangonels/AntiXrayHeuristicsIssues#1]
I don't care how you structure your ticket as long as it clearly includes at least all of the following:
**Server system:** Paper
**Minecraft version:** 1.14.4
**Steps to reproduce the issue:** Start xraying and find some diamonds. When the plugin starts to execute the command in the command section, the error will appear. Here's the link to the config: https://pastebin.com/kNmAsVuW
Following only if existent:
**Error log:** https://pastebin.com/d3cdg0QK
Following only if considered necesary or requested by developer:
**Link to config.yml file on https://gist.github.com:**

**Comment by Mangonels** [comment]
Damn Paper. The plugin is untested there. I'll check it out.

**Comment by Mangonels** [comment]
Let me know if it's solved on the latest build.

**Comment by Kyrobi** [comment]
It's fixed. Thanks!
