### ISSUE TITLE
[Suggestion] Events for DiscordSRV

### ISSUE THREAD

**Issue by thomaboehi** [Mangonels/AntiXrayHeuristicsIssues#10]
Hi!

I wanted to have a message send on a Discord channel. I use DiscordSRV and did something like that:
`
  - Trigger: /xrayer
    Channel: staff
    Content: "<@&638659020424740874>"
    Embed:
      Color: "#E60000"
      Author:
        ImageUrl: "http://cravatar.eu/helmavatar/${#args.get(0)}.png"
        Name: "${#args.get(0)}"
      Description: "a été détecté en tant que XRayer."
      Timestamp: true
`

That is not working, as expected.

What would be great is to be able to know Events that are used with this plugin, and hook up

**Comment by Mangonels** [comment]
AXH uses Bukkit's DispatchCommand() method for command execution with console as sender for all configurable commands in config. 

So basically all your commands are being executed as console.

Also, I really don't know how this particular DiscordSRV functionality works or what it even does. Try describing it if you want, but there's no guarantee I'll add what you are requesting. 

All I can ask for now is, can't AXH's command executions do this for you currently?

**Comment by thomaboehi** [comment]
Ok.
I tried but when AXH execute the command it says Unknow command.

The command isn't registered, can it be the problem? Because it isn't a "command", it is only a trigger..

But with DiscordSRV I can hook up to an event and when the event is triggered, DiscordSRV knows that it also must send the message. That's why I wanted to listen to any event that is triggered when a player is registered as an xrayer.

**Comment by Mangonels** [comment]
I'm asuming you're maybe asking for either:
- API functionality
- DiscordSRV compatibility with whatever the feature you're using does.

> I tried but when AXH execute the command it says Unknow command.
If it works from console with you executing it, it should work with AXH.

I'm still kinda confused on what the objective here is. I could consider your suggestion, but I really need a clear explanation on what exactly you need. And even so, I give no guarantee that this will be implemented, and if it is, no guarantee that it will be soon. Feel free to give it a go though.

**Comment by thomaboehi** [comment]
Ok I'll try to explain better when I'm at home

**Comment by thomaboehi** [comment]
Yes I'm asking for the API, I could have sayed that from beginning... Sorry.

And if you want to directly add DiscordSRV compatibility, it would be great.

**Comment by Mangonels** [comment]
I had an API planned for AXH, but I scrapped it out since I couldn't imagine anyone needing it, it shouldn't be too complicated to implement anyway, so I added it to the TODO list.

Direct DiscordSRV support could be added but I'd still need to understand exactly what I'm suposed to hook to.

**Comment by thomaboehi** [comment]
It is really special. I tried again to see if I was wrong but no.

When AXH executes the commands "xrayer {playername}" nothing happens, but when I run it from the console manually, it works. It always returns "Unknow command" but that's not really the point, it should work, as it is only a trigger.

**Comment by Mangonels** [comment]
So I made an API with some basic methods, and also made available an event which is called before handling an xrayer.

Idk if this will be useful to either you, or the developers of DiscordSRV somehow, but still, it's done. If there's any specific event you'd like to listen to, let me know and I'll add it if reasonable, else I'll consider this suggestion implemented for the upcoming 1.3.8 version.

**Comment by thomaboehi** [comment]
Hey! Thank you very much, I'll give it a try and tell you how it works and what I've done with the API :)

**Comment by Mangonels** [comment]
Keep in mind the API is not yet available on the current version, I'll be releasing 1.3.8 this Sunday, which will add the API functionality, but that one is going to only be compatible with mc 1.13+
I need to add compatibility on single jar in the future, for retro compatibility version 1.3.7 will be the only option for now.
