### ISSUE TITLE
[BUG] Worlds not being tracked

### ISSUE THREAD

**Issue by souldin1** [Mangonels/AntiXrayHeuristicsIssues#16]
**Server system:** [Spigot/Paper] Paper 
**Minecraft version:** 1.14.4
**Steps to reproduce the issue:** 
Everything is working but in worlds that i created and brought in outside of the normal worlds when creating the server are not being tracked. I have them in the Config just fine. 
**Error log:**
No errors just not tracking
**Link to config.yml file on gist.github.com:**
#AXH will only monitor player behaviour in order to detect xrays in certain worlds. Only nether and overworld world
#types will be considered from following lists:
TrackWorlds:
  - 'SteamCraft'
  - 'yucca'
  - 'Yucca'
  - 'Florian'
  - 'florian'
  - 'SteamCraft_nether'
  - SteamCraft
  - yucca
  - Yucca
  - Florian
  - florian

I put the worlds in every way possible to rule it out also. Main server world is SteamCraft.

**Comment by Mangonels** [comment]
There's no way I can tell for certain, because of the lack of a propper config paste, but I'd say you may have forgotten to quote some of your world names.

Additionally, AXH will probably not work as intended on non-vanilla world generations.

**Comment by souldin1** [comment]
Ya the other worlds are Brought in Via MultiVerse so not sure if that classifies as as normal Vanilla world.

**Comment by Mangonels** [comment]
How you loaded them on your server, doesn't matter, but rather how the terrains where generated, and also how the ores where generated (which is basically also terrain). The generation should be close to, or 100% vanilla, with default configurations (no configurations at all for that matter.
