### ISSUE TITLE
[Suggestion] AXH compatibility with Terra

### ISSUE THREAD

**Issue by JackAttack924** [Mangonels/AntiXrayHeuristicsIssues#18]
**Server system:** [Spigot/Paper]
**Minecraft version:** 1.16.5
**Steps to reproduce the issue:** Install Terra on default settings and try to xray
**Error log:** none
**Link to config.yml file on gist.github.com:**

I did not know whether to list this as a bug or suggestion so I apologize for that.
I saw a similar issue reported here about custom generation and axh not being able to detect it.
I have been messing around with the weights on my custom generation and have not been able to detect anything at all. Same no results show with default weights as well.

The custom generation plugin I use is called Terra
Inside Terra's plugin folder is Terra/packs/default.zip which contains all the instructions for the world generation I'm assuming.
Upon looking underground with xray, things look pretty vanilla to me, I could not find any huge veins or massive amount of specific ores.

Anyways I reach out to you in hope that maybe you are able to produce different results? If not its okay but I really do love your plugin and how efficient it is, there really is nothing better on the market. I felt the need to make a ticket for it instead of giving up.

Terra should include the default pack but ill throw mine in just in case too.
here is my discord if needed: Jack.#0148

[default.zip](https://github.com/Mangonels/AntiXrayHeuristicsIssues/files/5961789/default.zip)

**Comment by Mangonels** [comment]
AXH depends on 2 things:
1. Your ore scarcity, vein sizes and distribution.
2. The base block material for your underground terrain.

The two previous are bound to work fine if they are 100% (or close to) vanilla.

If your terrain is custom, it doesn't matter what plugin you used to generate it. The fact that u'r using a non-vanilla terrain on your server is what confuses AXH to be confused.

For this there are 2 factors that may help you, but still, I cannot promise anything:
1. For ore scarcity: You can tweak options on distance between ores in config.yml.
2. I'm working on https://github.com/Mangonels/AntiXrayHeuristicsIssues/issues/13 for unusual underground terrain materials, which you may configure once the next update is released.
