### ISSUE TITLE
[Suggestion] Change plugin.yml

### ISSUE THREAD

**Issue by Kyrobi** [Mangonels/AntiXrayHeuristicsIssues#2]
Currently if you change the name of the plugin in plugin.yml, the plugin will refuse to enable.

Why would I need to change it?

Prevent clients like Future from doing .plugins and seeing what antixray is on the server.

Request: 
Have the plugin still be able to load when the name in plugin.yml has been changed.

**Comment by Mangonels** [comment]
Sorry, I need to improve the notifications from github.

I'll take a look at that.

**Comment by Mangonels** [comment]
After a while taking a look at this, I must say I'm actually clueless as to how I could adapt this.

If you happen to know of any way, let me know. Else I will still ask on the spigot comunity for any possible workarounds.

**Comment by Mangonels** [comment]
Allthough I'm starting to suspect why It wouldn't load...

**Comment by Mangonels** [comment]
The plugin now loads when you change the name through the plugin.yml file. I hope this is enough for your case.

However, further issues may emerge related to internal plugin name changing. If so, please open a new ticket.

The updated version with this will come out breefly.
