### ISSUE TITLE
AXH doesnt work

### ISSUE THREAD

**Issue by russianpeanut** [Mangonels/AntiXrayHeuristicsIssues#30]
**Server system:** Paper
**Minecraft version:** 1.16.5
**Steps to reproduce the issue:**  It doesnt punish me i have xrayed for like 4 mins and found 48 diamonds i was making it very obvious i xrayed for every diamond i saw and also iron andit didnt punish me, i was deoped so no bypass perms and the plugin was like ignoring me. The worlds are correct
**Error log:** No error
**Link to config.yml file on gist.github.com:** https://gist.github.com/russianpeanut/fa4435fbee439ccf748ce11db797424e

**Comment by Mangonels** [comment]
Axh works fine on my 1.16.5 vanilla survival server.

What do you mean with "The worlds are correct", didn't you tell me that you were using a custom generated terrain?
As I explained. Custom generated terrains can produce a plethora of issues which may cause AXH to confuse internal ratings, or not detect anything at all. You may think you understand how AXH works internally, and may imagine that it's just a matter of mining ores in quick succession, but other factors come to play, and any diferences on how the world generates in vanilla vs how it generates custom, can cause these issues.

Care to give further details, else all I can say is that I already gave you the right answer on your previous ticket.

**Comment by russianpeanut** [comment]
Yes i did in the last ticket but i have 2 servers and that one i am talking about right now it the one with vanilla terrain

**Comment by russianpeanut** [comment]
nvm i looked in vault and there was one punished xrayer, weird it ignored me and i was deop

**Comment by Mangonels** [comment]
You could have also done something else which AXH may have ignored naturally due to it's design, like placing a bunch of ores on the surface and mining them all together expecting a detection?

**Comment by russianpeanut** [comment]
no i mined naturally spawned ores. I Could try bring some other player on the server what is defautly deoped and see if he gets punished

**Comment by russianpeanut** [comment]
ok so i told some player who was never opped on the server and he xrayed and he didnt get punished he mined alot of diamonds and debris he xrayed for like 15 minutes in "world" and "world_nether" with a diamond pickaxe

**Comment by Mangonels** [comment]
Are you using the default weights?

**Comment by russianpeanut** [comment]
What weights?

**Comment by Mangonels** [comment]
![image](https://user-images.githubusercontent.com/24245302/129487751-3d3991b3-1d35-4128-b9ef-7525fd04f337.png)

**Comment by russianpeanut** [comment]
Ok so if the weight is lower it means it will detect more but it increase false punishment chance?

**Comment by Mangonels** [comment]
> Ok so if the weight is lower it means it will detect more but it increase false punishment chance?

No, the other way around. Higher weights mean more sensibility, hence more chance of false positive.

Also, try the command **/axh xrayer <player>** and then check **/axh v** in order to confirm the registration system for xrayers is working, just in case.

**Comment by russianpeanut** [comment]
Yes axh xrayer works, i will try make the weight higher

**Comment by russianpeanut** [comment]
Great it works now Thank you alot

**Comment by russianpeanut** [comment]
also quick question i have 3x3 pickaxes on my server and AXH is detecting is as xray is there way to prevent it or i have to remove the 3x3 ability?

**Comment by russianpeanut** [comment]
Hi so i have set the wights back to default and now it falses everyone who mines like alot of diamonds in cave

**Comment by russianpeanut** [comment]
should i restart the server?

**Comment by Mangonels** [comment]
Reloading the plugin should be enough. Default weights should be fine. In essence, players won't be detected unless they mine a considerable amount quickly. What I really doubt is that the plugin is incapable of detecting at all, which is what you seem to claim, but don't worry, this ticket will remain open until we solve this, or AXH improves the core algorithm if it's really that terrible.

**Comment by russianpeanut** [comment]
its weird because i set it to default weights and it started detecting like it was higher, also in future updates if possible could you add support for advaned enchantements? Like when players mine with 3x3 enchant it wont detect it as xray because that happends too or if its the same bug

**Comment by russianpeanut** [comment]
its fixed thank you

**Comment by Mangonels** [comment]
Uh... so everything's in order I'm asuming. I'll close this, feel free to reopen/open new ticket.
