### ISSUE TITLE
I cant use AXH Commands... it says Invalid command argument.

### ISSUE THREAD

**Issue by RoyalClaims** [Mangonels/AntiXrayHeuristicsIssues#5]
however i tried everything... but it dont works.
I play on Paper Spigot 1.15.1

Only possible command is: /axh xrayer and absolve

But i cant look into the vault.

**Comment by Mangonels** [comment]
No one else reported this. I can use the vault myself on a clean Spigot server, and on my main server.
Even if you had "StoreCopy: false" or any other vault related config disabled, you should still be capable of executing /axh v

Just to confirm. Try /axh v, show me a screenshot of it not working.

**Comment by Mangonels** [comment]
This ticket is 5 days old, and hasn't been answered, so I'm going to asume this matter is solved.

Feel free to reopen the ticket if the issue re-emerges.
