### ISSUE TITLE
Don´t Work 

### ISSUE THREAD

**Issue by Cyber24-Dr** [Mangonels/AntiXrayHeuristicsIssues#7]
hey i have a problem , i have put the plugin on my test server where Paper 1.12.2 runs and would like to use it , the problem is it starts and shortly after the plugin is disabled again 

you can take a look at this 

https://prnt.sc/uw5gbf

**Comment by MithrandirCraft** [comment]
U'r using 1.9 API jar?

**Comment by Cyber24-Dr** [comment]
Yes i have use all 3 version nothing had function

**Comment by Mangonels** [comment]
Can't reproduce on Spigot... Could try paper but idk where the download for 1.12 is.
![image](https://user-images.githubusercontent.com/24245302/95800253-450f0600-0cf7-11eb-8502-f31880b85ff8.png)

**Comment by Mangonels** [comment]
I just uploaded a jar which is working for me, at least on Spigot. Reopen if this is not the case.
